name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Compose build
        run: |
          docker compose -f infra/docker-compose.yml config
          docker compose -f infra/docker-compose.yml build
